data <- c(23,24,30,32,45)
min_value <- min(data)
max_value <- max(data)
normalized_data_minmax <- (data - min_value) / (max_value - min_value)
print("Min-Max Normalized Data:")
print(normalized_data_minmax)
mean_value <- mean(data)
std_deviation <- sd(data)
normalized_data_zscore <- (data - mean_value) / std_deviation
print("Z-Score Normalized Data:")
print(normalized_data_zscore)
ds<-max_value/(10^2)
print("Decimal Scaling=")
print(ds)
